name: Continuous Integration
on:
  pull_request:

jobs:
  ci-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - uses: actions/cache@v3
        name: Define a cache for the tox based on the tox config file
        with:
          path: ./.tox
          key: tox-${{ hashFiles('tox.ini') }}
      - name: Run type checking
        run: poetry run pyrefly check

      - name: Run format check
        run: poetry run ruff format --diff
      - name: Run unit tests
        run: poetry run tox
      - name: Run lint
        run: poetry run ruff check --output-format=github .

  integration-tests:
    strategy:
      matrix:
        dialect: [mysql, postgresql, sqlite, mssql, clickhouse]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install --with inttests
      - name: Install atlas
        uses: ariga/setup-atlas@master
      - name: Run Test as Standalone
        working-directory: ./tests
        run: |
          atlas migrate diff --env sqlalchemy -c "file://atlas-standalone.hcl" --var dialect=${{ matrix.dialect }}
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
      - name: Verify migrations generated
        working-directory: ./tests
        run: |
          status=$(git status . --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env sqlalchemy' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
      - name: Run Test as Script
        working-directory: ./tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(cd ../ && pwd)
          atlas migrate diff --env sqlalchemy -c "file://atlas-script.hcl" --var dialect=${{ matrix.dialect }}
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
      - name: Verify migrations generated
        working-directory: ./tests
        run: |
          status=$(git status . --porcelain)
          if [ -n "$status" ]; then
            echo "you need to run 'atlas migrate diff --env sqlalchemy' and commit the changes"
            echo "$status"
            git --no-pager diff
            exit 1
           fi
      - name: Run Broken Models
        working-directory: ./tests
        run: |
          # dont fail if the command fails, just check the output
          output=$(atlas migrate diff --env sqlalchemy -c "file://atlas-standalone.hcl" --var dialect=mysql --var path="./testdata/broken" 2>&1 || true)
          expected_error="NameError: name 'DeclarativeBase' is not defined in testdata/broken/models.py"

          if [[ ! "$output" == *"$expected_error"* ]]; then
            echo "Expected command to fail with error message containing: $expected_error";
            echo "Instead got: $output";
            exit 1;
          fi
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
